name: msi_monitor
description: A medical simulation monitor for Android.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  flutter_reactive_ble: ^5.3.1
  flutter_ble_peripheral: ^2.0.0
  shared_preferences: ^2.2.2
  ble_peripheral: ^2.4.0          # The main package for BLE peripheral mode
  permission_handler: ^11.3.1     # For requesting Bluetooth permissions
  provider: ^6.1.2                # For state management
  google_fonts: ^6.2.1            # For the digital-style fonts
  lucide_icons: ^0.257.0           # For the icons in the UI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/beep.wav
    - assets/sounds/cuff.wav
